name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  packages: write
  contents: write

jobs:
  checks:
    name: Release Containers and Binaries
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: greenteagc
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.0-rc.3

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Show Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and Push Containers
        run: make all-container-push

      - name: Build Binaries
        run: make all-package

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/path-proxy-packages-latest/path-proxy*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
